spring:
  config:
    import:
      - "optional:classpath:bot-prod.yaml"
      - "optional:classpath:attribute.yaml"
      - "optional:classpath:dir_info.yaml"

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
    redis-channel:
      not-confirmed: not-confirmed
      group-not-confirmed: group-not-confirmed
      first-question: first-question
      group-first-question: group-first-question
      second-question: second-question
      group-second-question: group-second-question
      qr-sender: qr-sender
      group-qr-sender: group-qr-sender

logging:
  level:
    org.springframework: INFO
    ru.pereguzochka.telegram_bot: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"

bot-backend:
  host: http://192.168.31.103
  port: 8081

qr-code-url: src/main/resources/qr_code/qr.jpg
cut-off-choose-time: "3" #hours